- 
  nome: Ana Lígia
  filename: ana_ligia
  capitulos:
    F:
      inicio: |
        Oi Ana Lígia, espero que não tenha ocorrido problemas com a abertura dos novos PDFs?
        
        Você já pensou em aplicar algo que aprendeu na disciplina para organizar os processos da secretaria na escola em que trabalha?

        Em breve estaremos iniciando o projeto da disciplina, e você já poderia começar a pensar nisso.
- 
  nome: Ermeson
  filename: ermeson
  capitulos:
    F:
      inicio: |
        Oi Ermeson, gostei muito da sua participação na Web Conferência, e da presença na primeira avaliação.
        
        Em breve estaremos iniciando o projeto da disciplina, em que vamos utilizar os conhecimentos adquiridos na disciplina para realizar uma análise e projeto de um sistema simples.
        
        Você nos disse que ensina informática numa escola na sua cidade, em Pedra Branca,  você já pensou em projetar algum sistema para auxiliar no seu trabalho? 
        
        breve  você consegue pensar algo da sua escola que possamos utilizar no projeto final da disciplina?
        
        Você já pensou em aplicar algo que aprendeu na disciplina para organizar os processos da secretaria na escola em que trabalha?
- 
  nome: Adrielly
  filename: adrielly
  capitulos:
    F:
      inicio: |
        Olá Adrielly, gostei muito da sua presença na Web Conferência,
        porém senti sua falta na avaliação presencial, o que ocorreu?
        Não deixe de fazer a segunda avaliação e a reposição.
        
        Logo começaremos e projeto e já percebi que você entende muito bem da plataforma
        Moodle, já pensou em modelar alguma parte dela?
- 
  nome: Waldirene
  filename: waldirene
  capitulos:
    F:
      inicio: |
        Olá Waldirene, gostei muito da sua presença na Web Conferência,
        porém senti sua falta na avaliação presencial, o que ocorreu?
        Não deixe de fazer a segunda avaliação e a reposição.
        
        Logo começaremos e projeto e já percebi que você entende muito bem da plataforma
        Moodle, já pensou em modelar alguma parte dela?